version: "3"
services:
  web:
    container_name: ktftime-web
    build:
      context: .
      dockerfile: Dockerfile_web
    image: ktftime-web:v1
    ports:
      - "4000:4000"
    links:
      - db 
    depends_on:
      - db

  db:
    container_name: ktftime-db
    build:
      context: .
      dockerfile: Dockerfile_db
    image: ktftime-db:v1
    environment:
      - MONGO_DATA_DIR=/data/db/
    restart: always

